# Resource Adapter
quarkus.ironjacamar.ra.kind=artemis
quarkus.ironjacamar.ra.config.connection-parameters=host=localhost;port=61616;protocols=AMQP
quarkus.ironjacamar.ra.config.user=guest
quarkus.ironjacamar.ra.config.password=guest

# Disable idle remover
quarkus.ironjacamar.ra.cm.pool.config.idle-timeout-minutes=0

# Reactive Messaging incoming channel backed by IronJacamar
mp.messaging.incoming.test-queue.connector=ironjacamar
mp.messaging.incoming.test-queue.resource-adapter-kind=artemis
mp.messaging.incoming.test-queue.destination=TestQueue
mp.messaging.incoming.test-queue.destination-type=jakarta.jms.Queue
mp.messaging.incoming.test-queue.max-session=2

# Reactive Messaging outgoing channel backed by IronJacamar
mp.messaging.outgoing.out-queue.connector=ironjacamar
mp.messaging.outgoing.out-queue.resource-adapter-kind=artemis
mp.messaging.outgoing.out-queue.destination=OutQueue
mp.messaging.outgoing.out-queue.destination-type=jakarta.jms.Queue

quarkus.log.category."org.apache.activemq.audit".level=WARN
